services:
  - type: web
    name: minha-agencia-spring
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
